server.port=8088
spring.mvc.pathmatch.use-suffix-pattern=false

# 文件上传配置
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

# Hive 连接配置
hive.url=jdbc:hive2://121.4.19.133:10000/default
hive.user=ubuntu
hive.password=
